fix(mdns): Refactor fuzzer test suite

diff --git a/.github/workflows/mdns__host-tests.yml b/.github/workflows/mdns__host-tests.yml
--- a/.github/workflows/mdns__host-tests.yml
+++ b/.github/workflows/mdns__host-tests.yml
@@ -55,8 +55,11 @@ jobs:
         shell: bash
         run: |
           . ${IDF_PATH}/export.sh
-          cd components/mdns/tests/test_afl_fuzz_host/
-          make INSTR=off
+          cd components/mdns/tests/host_unit_test/
+          idf.py reconfigure
+          mkdir build2 && cd build2
+          cmake ..
+          cmake --build .
       - name: Test no malloc functions
         shell: bash
         run: |
@@ -99,13 +102,28 @@ jobs:
         shell: bash
         run: |
           export IDF_PATH=$GITHUB_WORKSPACE/idf
-          cd components/mdns/tests/test_afl_fuzz_host/
-          make fuzz
+          cd components/mdns/tests/host_unit_test/
+          pip install dnslib
+          cd input && python generate_cases.py && cd ..
+          mkdir build2 && cd build2
+          cmake -DCMAKE_C_COMPILER=afl-cc ..
+          cmake --build .
+          cd ..
+          timeout 10m afl-fuzz -i input -o out -- build2/mdns_host_unit_test || \
+          if [ $? -eq 124 ]; then  # timeout exit code
+            if [ -n "$(find out/default/crashes -type f 2>/dev/null)" ]; then
+              echo "Crashes found!";
+              tar -czf out/default/crashes.tar.gz -C out/default crashes;
+              exit 1;
+            fi
+          else
+            exit 1;
+          fi
 
       - name: Upload Crash Artifacts
         if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: fuzz-crashes
-          path: components/mdns/tests/test_afl_fuzz_host/out/default/crashes.tar.gz
+          path: components/mdns/tests/host_unit_test/out/default/crashes.tar.gz
           if-no-files-found: ignore
